// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleManagement.Data;

#nullable disable

namespace VehicleManagement.Migrations
{
    [DbContext(typeof(VehicleDbContext))]
    [Migration("20241010123845_InitVehicleDb")]
    partial class InitVehicleDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VehicleManagement.Models.Auto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("VehicleId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Color")
                        .HasColumnType("int");

                    b.Property<string>("Fuel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TopSpeed")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Color = 162,
                            Fuel = "Gasoline",
                            Manufacturer = "Bentley",
                            Model = "Roadster",
                            TopSpeed = 200,
                            Type = "Passenger Van"
                        },
                        new
                        {
                            Id = 2L,
                            Color = 89,
                            Fuel = "Hybrid",
                            Manufacturer = "Jeep",
                            Model = "Ranchero",
                            TopSpeed = 160,
                            Type = "Wagon"
                        },
                        new
                        {
                            Id = 3L,
                            Color = 94,
                            Fuel = "Gasoline",
                            Manufacturer = "Maserati",
                            Model = "Aventador",
                            TopSpeed = 120,
                            Type = "Sedan"
                        },
                        new
                        {
                            Id = 4L,
                            Color = 139,
                            Fuel = "Hybrid",
                            Manufacturer = "Jaguar",
                            Model = "Volt",
                            TopSpeed = 120,
                            Type = "Minivan"
                        },
                        new
                        {
                            Id = 5L,
                            Color = 88,
                            Fuel = "Hybrid",
                            Manufacturer = "Volvo",
                            Model = "Aventador",
                            TopSpeed = 140,
                            Type = "Sedan"
                        },
                        new
                        {
                            Id = 6L,
                            Color = 86,
                            Fuel = "Electric",
                            Manufacturer = "Nissan",
                            Model = "Element",
                            TopSpeed = 180,
                            Type = "Sedan"
                        },
                        new
                        {
                            Id = 7L,
                            Color = 155,
                            Fuel = "Hybrid",
                            Manufacturer = "Land Rover",
                            Model = "Camry",
                            TopSpeed = 190,
                            Type = "Extended Cab Pickup"
                        },
                        new
                        {
                            Id = 8L,
                            Color = 154,
                            Fuel = "Gasoline",
                            Manufacturer = "Fiat",
                            Model = "Expedition",
                            TopSpeed = 120,
                            Type = "Minivan"
                        },
                        new
                        {
                            Id = 9L,
                            Color = 159,
                            Fuel = "Electric",
                            Manufacturer = "Dodge",
                            Model = "Countach",
                            TopSpeed = 160,
                            Type = "Coupe"
                        },
                        new
                        {
                            Id = 10L,
                            Color = 115,
                            Fuel = "Gasoline",
                            Manufacturer = "Toyota",
                            Model = "V90",
                            TopSpeed = 160,
                            Type = "Crew Cab Pickup"
                        },
                        new
                        {
                            Id = 11L,
                            Color = 132,
                            Fuel = "Electric",
                            Manufacturer = "Mini",
                            Model = "Volt",
                            TopSpeed = 130,
                            Type = "Coupe"
                        },
                        new
                        {
                            Id = 12L,
                            Color = 70,
                            Fuel = "Hybrid",
                            Manufacturer = "Dodge",
                            Model = "LeBaron",
                            TopSpeed = 180,
                            Type = "Passenger Van"
                        },
                        new
                        {
                            Id = 13L,
                            Color = 69,
                            Fuel = "Hybrid",
                            Manufacturer = "Kia",
                            Model = "Cruze",
                            TopSpeed = 180,
                            Type = "Extended Cab Pickup"
                        },
                        new
                        {
                            Id = 14L,
                            Color = 73,
                            Fuel = "Electric",
                            Manufacturer = "Ford",
                            Model = "Fiesta",
                            TopSpeed = 160,
                            Type = "Hatchback"
                        },
                        new
                        {
                            Id = 15L,
                            Color = 45,
                            Fuel = "Electric",
                            Manufacturer = "Mazda",
                            Model = "Grand Caravan",
                            TopSpeed = 210,
                            Type = "Hatchback"
                        },
                        new
                        {
                            Id = 16L,
                            Color = 94,
                            Fuel = "Electric",
                            Manufacturer = "Ferrari",
                            Model = "CTS",
                            TopSpeed = 160,
                            Type = "Wagon"
                        },
                        new
                        {
                            Id = 17L,
                            Color = 136,
                            Fuel = "Diesel",
                            Manufacturer = "Ferrari",
                            Model = "911",
                            TopSpeed = 170,
                            Type = "Cargo Van"
                        },
                        new
                        {
                            Id = 18L,
                            Color = 130,
                            Fuel = "Gasoline",
                            Manufacturer = "Ferrari",
                            Model = "911",
                            TopSpeed = 170,
                            Type = "Convertible"
                        },
                        new
                        {
                            Id = 19L,
                            Color = 110,
                            Fuel = "Gasoline",
                            Manufacturer = "Hyundai",
                            Model = "1",
                            TopSpeed = 120,
                            Type = "Wagon"
                        },
                        new
                        {
                            Id = 20L,
                            Color = 154,
                            Fuel = "Diesel",
                            Manufacturer = "Bentley",
                            Model = "Ranchero",
                            TopSpeed = 180,
                            Type = "Crew Cab Pickup"
                        },
                        new
                        {
                            Id = 21L,
                            Color = 47,
                            Fuel = "Electric",
                            Manufacturer = "Mercedes Benz",
                            Model = "XC90",
                            TopSpeed = 120,
                            Type = "Convertible"
                        },
                        new
                        {
                            Id = 22L,
                            Color = 125,
                            Fuel = "Hybrid",
                            Manufacturer = "Mini",
                            Model = "Ranchero",
                            TopSpeed = 170,
                            Type = "Cargo Van"
                        },
                        new
                        {
                            Id = 23L,
                            Color = 145,
                            Fuel = "Hybrid",
                            Manufacturer = "Smart",
                            Model = "Jetta",
                            TopSpeed = 140,
                            Type = "Convertible"
                        },
                        new
                        {
                            Id = 24L,
                            Color = 59,
                            Fuel = "Diesel",
                            Manufacturer = "Mini",
                            Model = "Explorer",
                            TopSpeed = 220,
                            Type = "Sedan"
                        },
                        new
                        {
                            Id = 25L,
                            Color = 47,
                            Fuel = "Diesel",
                            Manufacturer = "Bentley",
                            Model = "Expedition",
                            TopSpeed = 160,
                            Type = "Passenger Van"
                        },
                        new
                        {
                            Id = 26L,
                            Color = 143,
                            Fuel = "Hybrid",
                            Manufacturer = "Lamborghini",
                            Model = "Fiesta",
                            TopSpeed = 150,
                            Type = "Hatchback"
                        },
                        new
                        {
                            Id = 27L,
                            Color = 38,
                            Fuel = "Gasoline",
                            Manufacturer = "Mini",
                            Model = "CTS",
                            TopSpeed = 130,
                            Type = "Hatchback"
                        },
                        new
                        {
                            Id = 28L,
                            Color = 58,
                            Fuel = "Gasoline",
                            Manufacturer = "Tesla",
                            Model = "Grand Cherokee",
                            TopSpeed = 150,
                            Type = "Passenger Van"
                        },
                        new
                        {
                            Id = 29L,
                            Color = 123,
                            Fuel = "Hybrid",
                            Manufacturer = "Fiat",
                            Model = "LeBaron",
                            TopSpeed = 160,
                            Type = "Extended Cab Pickup"
                        },
                        new
                        {
                            Id = 30L,
                            Color = 164,
                            Fuel = "Hybrid",
                            Manufacturer = "Smart",
                            Model = "Accord",
                            TopSpeed = 130,
                            Type = "Sedan"
                        },
                        new
                        {
                            Id = 31L,
                            Color = 93,
                            Fuel = "Electric",
                            Manufacturer = "Kia",
                            Model = "Civic",
                            TopSpeed = 190,
                            Type = "Wagon"
                        },
                        new
                        {
                            Id = 32L,
                            Color = 174,
                            Fuel = "Gasoline",
                            Manufacturer = "Hyundai",
                            Model = "Model T",
                            TopSpeed = 180,
                            Type = "Minivan"
                        },
                        new
                        {
                            Id = 33L,
                            Color = 108,
                            Fuel = "Electric",
                            Manufacturer = "Ford",
                            Model = "El Camino",
                            TopSpeed = 170,
                            Type = "Wagon"
                        },
                        new
                        {
                            Id = 34L,
                            Color = 80,
                            Fuel = "Hybrid",
                            Manufacturer = "Hyundai",
                            Model = "Model S",
                            TopSpeed = 150,
                            Type = "Passenger Van"
                        },
                        new
                        {
                            Id = 35L,
                            Color = 117,
                            Fuel = "Diesel",
                            Manufacturer = "Cadillac",
                            Model = "Charger",
                            TopSpeed = 200,
                            Type = "Cargo Van"
                        },
                        new
                        {
                            Id = 36L,
                            Color = 42,
                            Fuel = "Hybrid",
                            Manufacturer = "Ford",
                            Model = "Civic",
                            TopSpeed = 180,
                            Type = "Extended Cab Pickup"
                        },
                        new
                        {
                            Id = 37L,
                            Color = 127,
                            Fuel = "Diesel",
                            Manufacturer = "Land Rover",
                            Model = "Element",
                            TopSpeed = 200,
                            Type = "Hatchback"
                        },
                        new
                        {
                            Id = 38L,
                            Color = 175,
                            Fuel = "Diesel",
                            Manufacturer = "Mercedes Benz",
                            Model = "Jetta",
                            TopSpeed = 190,
                            Type = "Minivan"
                        },
                        new
                        {
                            Id = 39L,
                            Color = 30,
                            Fuel = "Hybrid",
                            Manufacturer = "Chevrolet",
                            Model = "Model 3",
                            TopSpeed = 180,
                            Type = "Convertible"
                        },
                        new
                        {
                            Id = 40L,
                            Color = 86,
                            Fuel = "Hybrid",
                            Manufacturer = "Maserati",
                            Model = "El Camino",
                            TopSpeed = 170,
                            Type = "Passenger Van"
                        },
                        new
                        {
                            Id = 41L,
                            Color = 38,
                            Fuel = "Hybrid",
                            Manufacturer = "Lamborghini",
                            Model = "Sentra",
                            TopSpeed = 220,
                            Type = "Minivan"
                        },
                        new
                        {
                            Id = 42L,
                            Color = 144,
                            Fuel = "Electric",
                            Manufacturer = "Land Rover",
                            Model = "Altima",
                            TopSpeed = 210,
                            Type = "Wagon"
                        },
                        new
                        {
                            Id = 43L,
                            Color = 170,
                            Fuel = "Gasoline",
                            Manufacturer = "Hyundai",
                            Model = "Expedition",
                            TopSpeed = 200,
                            Type = "Wagon"
                        },
                        new
                        {
                            Id = 44L,
                            Color = 97,
                            Fuel = "Gasoline",
                            Manufacturer = "Honda",
                            Model = "Grand Cherokee",
                            TopSpeed = 130,
                            Type = "Convertible"
                        },
                        new
                        {
                            Id = 45L,
                            Color = 86,
                            Fuel = "Diesel",
                            Manufacturer = "Mercedes Benz",
                            Model = "Alpine",
                            TopSpeed = 190,
                            Type = "Convertible"
                        },
                        new
                        {
                            Id = 46L,
                            Color = 164,
                            Fuel = "Hybrid",
                            Manufacturer = "Ferrari",
                            Model = "Grand Cherokee",
                            TopSpeed = 130,
                            Type = "Crew Cab Pickup"
                        },
                        new
                        {
                            Id = 47L,
                            Color = 66,
                            Fuel = "Gasoline",
                            Manufacturer = "Smart",
                            Model = "Countach",
                            TopSpeed = 190,
                            Type = "Minivan"
                        },
                        new
                        {
                            Id = 48L,
                            Color = 63,
                            Fuel = "Electric",
                            Manufacturer = "Chrysler",
                            Model = "Element",
                            TopSpeed = 210,
                            Type = "Wagon"
                        },
                        new
                        {
                            Id = 49L,
                            Color = 159,
                            Fuel = "Hybrid",
                            Manufacturer = "Rolls Royce",
                            Model = "Wrangler",
                            TopSpeed = 220,
                            Type = "Extended Cab Pickup"
                        },
                        new
                        {
                            Id = 50L,
                            Color = 152,
                            Fuel = "Gasoline",
                            Manufacturer = "Jaguar",
                            Model = "Altima",
                            TopSpeed = 210,
                            Type = "Hatchback"
                        },
                        new
                        {
                            Id = 51L,
                            Color = 91,
                            Fuel = "Electric",
                            Manufacturer = "Chrysler",
                            Model = "Civic",
                            TopSpeed = 160,
                            Type = "Convertible"
                        },
                        new
                        {
                            Id = 52L,
                            Color = 119,
                            Fuel = "Diesel",
                            Manufacturer = "Toyota",
                            Model = "CTS",
                            TopSpeed = 190,
                            Type = "Hatchback"
                        },
                        new
                        {
                            Id = 53L,
                            Color = 143,
                            Fuel = "Gasoline",
                            Manufacturer = "Kia",
                            Model = "Fortwo",
                            TopSpeed = 180,
                            Type = "Crew Cab Pickup"
                        },
                        new
                        {
                            Id = 54L,
                            Color = 159,
                            Fuel = "Gasoline",
                            Manufacturer = "Chevrolet",
                            Model = "Escalade",
                            TopSpeed = 200,
                            Type = "Wagon"
                        },
                        new
                        {
                            Id = 55L,
                            Color = 147,
                            Fuel = "Diesel",
                            Manufacturer = "Smart",
                            Model = "Aventador",
                            TopSpeed = 160,
                            Type = "Sedan"
                        },
                        new
                        {
                            Id = 56L,
                            Color = 38,
                            Fuel = "Hybrid",
                            Manufacturer = "Nissan",
                            Model = "F-150",
                            TopSpeed = 200,
                            Type = "Convertible"
                        },
                        new
                        {
                            Id = 57L,
                            Color = 109,
                            Fuel = "Gasoline",
                            Manufacturer = "Porsche",
                            Model = "Alpine",
                            TopSpeed = 120,
                            Type = "Passenger Van"
                        },
                        new
                        {
                            Id = 58L,
                            Color = 154,
                            Fuel = "Electric",
                            Manufacturer = "Bentley",
                            Model = "Silverado",
                            TopSpeed = 170,
                            Type = "Coupe"
                        },
                        new
                        {
                            Id = 59L,
                            Color = 150,
                            Fuel = "Gasoline",
                            Manufacturer = "Kia",
                            Model = "Expedition",
                            TopSpeed = 160,
                            Type = "Wagon"
                        },
                        new
                        {
                            Id = 60L,
                            Color = 148,
                            Fuel = "Gasoline",
                            Manufacturer = "Maserati",
                            Model = "Corvette",
                            TopSpeed = 210,
                            Type = "Coupe"
                        },
                        new
                        {
                            Id = 61L,
                            Color = 141,
                            Fuel = "Diesel",
                            Manufacturer = "Ford",
                            Model = "2",
                            TopSpeed = 130,
                            Type = "Sedan"
                        },
                        new
                        {
                            Id = 62L,
                            Color = 46,
                            Fuel = "Electric",
                            Manufacturer = "Polestar",
                            Model = "Fiesta",
                            TopSpeed = 150,
                            Type = "SUV"
                        },
                        new
                        {
                            Id = 63L,
                            Color = 171,
                            Fuel = "Hybrid",
                            Manufacturer = "Volkswagen",
                            Model = "Alpine",
                            TopSpeed = 210,
                            Type = "Hatchback"
                        },
                        new
                        {
                            Id = 64L,
                            Color = 156,
                            Fuel = "Hybrid",
                            Manufacturer = "Honda",
                            Model = "PT Cruiser",
                            TopSpeed = 150,
                            Type = "Coupe"
                        },
                        new
                        {
                            Id = 65L,
                            Color = 150,
                            Fuel = "Electric",
                            Manufacturer = "Jeep",
                            Model = "Roadster",
                            TopSpeed = 190,
                            Type = "Extended Cab Pickup"
                        },
                        new
                        {
                            Id = 66L,
                            Color = 119,
                            Fuel = "Hybrid",
                            Manufacturer = "Tesla",
                            Model = "Escalade",
                            TopSpeed = 170,
                            Type = "Passenger Van"
                        },
                        new
                        {
                            Id = 67L,
                            Color = 155,
                            Fuel = "Diesel",
                            Manufacturer = "Honda",
                            Model = "PT Cruiser",
                            TopSpeed = 180,
                            Type = "Crew Cab Pickup"
                        },
                        new
                        {
                            Id = 68L,
                            Color = 123,
                            Fuel = "Gasoline",
                            Manufacturer = "Mini",
                            Model = "Beetle",
                            TopSpeed = 160,
                            Type = "Convertible"
                        },
                        new
                        {
                            Id = 69L,
                            Color = 79,
                            Fuel = "Electric",
                            Manufacturer = "BMW",
                            Model = "CX-9",
                            TopSpeed = 120,
                            Type = "Convertible"
                        },
                        new
                        {
                            Id = 70L,
                            Color = 105,
                            Fuel = "Hybrid",
                            Manufacturer = "Rolls Royce",
                            Model = "Altima",
                            TopSpeed = 120,
                            Type = "Sedan"
                        },
                        new
                        {
                            Id = 71L,
                            Color = 156,
                            Fuel = "Electric",
                            Manufacturer = "Polestar",
                            Model = "XTS",
                            TopSpeed = 220,
                            Type = "SUV"
                        },
                        new
                        {
                            Id = 72L,
                            Color = 128,
                            Fuel = "Diesel",
                            Manufacturer = "Smart",
                            Model = "Accord",
                            TopSpeed = 140,
                            Type = "Cargo Van"
                        },
                        new
                        {
                            Id = 73L,
                            Color = 128,
                            Fuel = "Electric",
                            Manufacturer = "Mercedes Benz",
                            Model = "CTS",
                            TopSpeed = 120,
                            Type = "Convertible"
                        },
                        new
                        {
                            Id = 74L,
                            Color = 175,
                            Fuel = "Gasoline",
                            Manufacturer = "Audi",
                            Model = "XC90",
                            TopSpeed = 180,
                            Type = "Passenger Van"
                        },
                        new
                        {
                            Id = 75L,
                            Color = 163,
                            Fuel = "Hybrid",
                            Manufacturer = "Lamborghini",
                            Model = "Escalade",
                            TopSpeed = 180,
                            Type = "Extended Cab Pickup"
                        },
                        new
                        {
                            Id = 76L,
                            Color = 129,
                            Fuel = "Hybrid",
                            Manufacturer = "Volkswagen",
                            Model = "XC90",
                            TopSpeed = 200,
                            Type = "Sedan"
                        },
                        new
                        {
                            Id = 77L,
                            Color = 52,
                            Fuel = "Gasoline",
                            Manufacturer = "Dodge",
                            Model = "Jetta",
                            TopSpeed = 120,
                            Type = "Minivan"
                        },
                        new
                        {
                            Id = 78L,
                            Color = 98,
                            Fuel = "Diesel",
                            Manufacturer = "Chevrolet",
                            Model = "Explorer",
                            TopSpeed = 190,
                            Type = "Cargo Van"
                        },
                        new
                        {
                            Id = 79L,
                            Color = 47,
                            Fuel = "Diesel",
                            Manufacturer = "Mini",
                            Model = "Accord",
                            TopSpeed = 130,
                            Type = "Coupe"
                        },
                        new
                        {
                            Id = 80L,
                            Color = 46,
                            Fuel = "Electric",
                            Manufacturer = "Kia",
                            Model = "Escalade",
                            TopSpeed = 160,
                            Type = "Crew Cab Pickup"
                        },
                        new
                        {
                            Id = 81L,
                            Color = 44,
                            Fuel = "Electric",
                            Manufacturer = "Bentley",
                            Model = "Beetle",
                            TopSpeed = 130,
                            Type = "Convertible"
                        },
                        new
                        {
                            Id = 82L,
                            Color = 91,
                            Fuel = "Gasoline",
                            Manufacturer = "Volkswagen",
                            Model = "Spyder",
                            TopSpeed = 210,
                            Type = "Cargo Van"
                        },
                        new
                        {
                            Id = 83L,
                            Color = 40,
                            Fuel = "Electric",
                            Manufacturer = "Volvo",
                            Model = "Volt",
                            TopSpeed = 190,
                            Type = "Cargo Van"
                        },
                        new
                        {
                            Id = 84L,
                            Color = 107,
                            Fuel = "Diesel",
                            Manufacturer = "Audi",
                            Model = "Malibu",
                            TopSpeed = 140,
                            Type = "Crew Cab Pickup"
                        },
                        new
                        {
                            Id = 85L,
                            Color = 131,
                            Fuel = "Hybrid",
                            Manufacturer = "BMW",
                            Model = "Land Cruiser",
                            TopSpeed = 140,
                            Type = "Minivan"
                        },
                        new
                        {
                            Id = 86L,
                            Color = 67,
                            Fuel = "Hybrid",
                            Manufacturer = "Tesla",
                            Model = "XTS",
                            TopSpeed = 210,
                            Type = "Passenger Van"
                        },
                        new
                        {
                            Id = 87L,
                            Color = 166,
                            Fuel = "Diesel",
                            Manufacturer = "Tesla",
                            Model = "ATS",
                            TopSpeed = 200,
                            Type = "Convertible"
                        },
                        new
                        {
                            Id = 88L,
                            Color = 37,
                            Fuel = "Electric",
                            Manufacturer = "Tesla",
                            Model = "Sentra",
                            TopSpeed = 130,
                            Type = "Hatchback"
                        },
                        new
                        {
                            Id = 89L,
                            Color = 77,
                            Fuel = "Electric",
                            Manufacturer = "Nissan",
                            Model = "V90",
                            TopSpeed = 160,
                            Type = "Convertible"
                        },
                        new
                        {
                            Id = 90L,
                            Color = 103,
                            Fuel = "Hybrid",
                            Manufacturer = "Honda",
                            Model = "A8",
                            TopSpeed = 170,
                            Type = "Cargo Van"
                        },
                        new
                        {
                            Id = 91L,
                            Color = 80,
                            Fuel = "Diesel",
                            Manufacturer = "Maserati",
                            Model = "CX-9",
                            TopSpeed = 160,
                            Type = "Minivan"
                        },
                        new
                        {
                            Id = 92L,
                            Color = 113,
                            Fuel = "Gasoline",
                            Manufacturer = "Chrysler",
                            Model = "Challenger",
                            TopSpeed = 140,
                            Type = "Minivan"
                        },
                        new
                        {
                            Id = 93L,
                            Color = 108,
                            Fuel = "Hybrid",
                            Manufacturer = "Bugatti",
                            Model = "Escalade",
                            TopSpeed = 150,
                            Type = "Crew Cab Pickup"
                        },
                        new
                        {
                            Id = 94L,
                            Color = 142,
                            Fuel = "Diesel",
                            Manufacturer = "Maserati",
                            Model = "Prius",
                            TopSpeed = 220,
                            Type = "Passenger Van"
                        },
                        new
                        {
                            Id = 95L,
                            Color = 63,
                            Fuel = "Hybrid",
                            Manufacturer = "Honda",
                            Model = "Wrangler",
                            TopSpeed = 170,
                            Type = "Hatchback"
                        },
                        new
                        {
                            Id = 96L,
                            Color = 32,
                            Fuel = "Diesel",
                            Manufacturer = "Mini",
                            Model = "Silverado",
                            TopSpeed = 130,
                            Type = "Convertible"
                        },
                        new
                        {
                            Id = 97L,
                            Color = 162,
                            Fuel = "Hybrid",
                            Manufacturer = "Ford",
                            Model = "Golf",
                            TopSpeed = 180,
                            Type = "Crew Cab Pickup"
                        },
                        new
                        {
                            Id = 98L,
                            Color = 174,
                            Fuel = "Hybrid",
                            Manufacturer = "Bentley",
                            Model = "Escalade",
                            TopSpeed = 140,
                            Type = "Cargo Van"
                        },
                        new
                        {
                            Id = 99L,
                            Color = 133,
                            Fuel = "Gasoline",
                            Manufacturer = "Ferrari",
                            Model = "Challenger",
                            TopSpeed = 120,
                            Type = "Cargo Van"
                        },
                        new
                        {
                            Id = 100L,
                            Color = 147,
                            Fuel = "Electric",
                            Manufacturer = "Rolls Royce",
                            Model = "Civic",
                            TopSpeed = 210,
                            Type = "Cargo Van"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
